#!/bin/bash
# The command to build the Angular project so that it can be served by Github pages.
# The angular.json file should have the outputPath set to the dist directory only:
# "outputPath": "dist",

# Build for github
ng build --base-href "https://chess.davidgma.com/"
