#!/bin/bash
# The command to build the Angular project so that it can be served by Github pages.
# The angular.json file should have the outputPath set to the dist directory only:
# "outputPath": "dist",
# The Github setting for pages should choose the gh-pages branch.
# npm install -g angular-cli-ghpages


if [ $# -gt 0 ]; then
	message=$*
else
	message="Upload changes."
fi

echo $message

# Create a local copy and serve it
ng build #--base-href "http://localhost:4201/"
rm -r ~/local/web/chess-opening-trainer
mkdir -p ~/local/web/chess-opening-trainer
cp ./dist/*  ~/local/web/chess-opening-trainer
server="busybox httpd -p 4201"
pids=`ps -e -o pid,args | grep "$server" | cut -d' ' -f2`
pid=$( echo $pids | cut -d' ' -f1)
#echo $pid
kill $pid
screen -d -m bash -c "$server -h ~/local/web/chess-opening-trainer; exec sh"

# Build for github
ng build --base-href "https://davidgma.github.io/chess-opening-trainer/"
git add *
git commit -a -m "${message}"
git push
ngh

# Website https://davidgma.github.io/google-sheets-demo
